version: "3.8"

networks:
  authentication-challenge-nw:
    name: authentication-challenge-nw
    driver: bridge

services:
  auth_db: &db
    container_name: auth_db
    hostname: auth_db
    image: postgres:16
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 15s
      retries: 3
      start_period: 5s
    ports:
      - "5432:5432"
    networks:
      - authentication-challenge-nw

#  debts_db:
#    <<: *db
#    container_name: debts_db
#    hostname: debts_db
#    environment:
#      POSTGRES_DB: debts_db
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root
#    ports:
#      - "5433:5432"

  auth_app: &app
    container_name: auth_app
    hostname: auth_app
    build:
      context: ./auth
    ports:
      - "3000:3001"
    networks:
      - authentication-challenge-nw
