### Create user
POST http://{{host}}:{{authPort}}/auth/users
Content-Type: application/json

{
  "cpf": "72430024985",
  "nome": "Jhon Doe",
  "nascimento": "1996-03-06",
  "email": "jhon@doe.com",
  "senha": "Jd1996"
}

### Login (Session token)
POST http://{{host}}:{{authPort}}/auth/users/login
Content-Type: application/json

{
  "cpf": "72430024985",
  "senha": "Jd1996"
}